spring:
  datasource:
    url: jdbc:h2:mem:spring
    driverClassName: org.h2.Driver
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /spring
      settings:
        trace: false
        web-allow-others: false